### ISSUE TITLE
requeu machine for volume resize without changes of size for empty disks

### ISSUE THREAD

**Issue by lukas016** [ironcore-dev/libvirt-provider#116]
**Bug Description**
Machine is reconciled in infinity loop trigger by volume-resize logic.
Probably root cause is missing lastSize (null) in volume-resize:

```
2024-01-16T14:59:48Z	DEBUG	machine-reconciler.volume-size	Enqueue machine: Volume Size changed	{"volumeName": "ephe-disk", "machineID": "24f94321-fc62-424d-8d1b-bb693e18b88e", "lastSize": null, "volumeSize": 5368709120}
2024-01-16T14:59:48Z	LEVEL(-2)	machine-reconciler	Getting machine from store	{"machineId": "24f94321-fc62-424d-8d1b-bb693e18b88e", "id": "24f94321-fc62-424d-8d1b-bb693e18b88e"}
```

**To Reproduce**
1. Create machine with 2 empty disk
2. Check logs

**Expected behavior**
Don't trigger reconcile loop, if volume sizes are the same.

**Comment by so-sahu** [comment]
Below is my analysis of this issue:

- The `getLastVolumeSize` function is designed to check for the handle/volumeID. However, when used within `startCheckAndEnqueueVolumeResize`, it references volume.Name instead. As a result, the lastSize becomes null (refer to [link](https://github.com/ironcore-dev/libvirt-provider/blob/5b55da5d15e978f796b9b51d6989a3c5223245e5/pkg/controllers/machine_controller.go#L221)).

- Another issue in the code arises when creating an empty disk. Initially, the disk is created with the size specified in the specification. However, in subsequent iterations, the size is set to the default value (refer to [link](https://github.com/ironcore-dev/libvirt-provider/blob/5b55da5d15e978f796b9b51d6989a3c5223245e5/pkg/plugins/volume/emptydisk/emptydisk.go#L77)) because the raw disk file already exists (refer to [link](https://github.com/ironcore-dev/libvirt-provider/blob/5b55da5d15e978f796b9b51d6989a3c5223245e5/pkg/plugins/volume/emptydisk/emptydisk.go#L79)). The size set in the status is then incorrectly interpreted as a change in volume, leading to unexpected behavior in the volume-resize logic.

- As the current volume resize implementations exclusively support Ceph volumes, consideration of empty disks for requeue should be excluded.
